spring:
    application:
        name: notification-service

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    
    cloud:
        stream:
            default-binder: kafka
            bindings:
                employeeEvent-in-0:
                    destination: employee-topic
                    content-type: text/plain

    kafka:
        bootstrap-servers: localhost:9092

        consumer:
            group-id: employee-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
    port: 9091
